import type {Config} from 'tailwindcss'

const config:Config = {
    darkMode :'class',
    theme : {
        extend : {
            colors : {
              "on-surface": "#e5e2e1",
              "on-secondary-fixed": "#001a41",
              "background": "#0e0e0e",
              "secondary-fixed": "#d8e2ff",
              "outline": "#8b90a0",
              "on-error": "#690005",
              "surface-container-low": "#1c1b1b",
              "surface-tint": "#2ddbde",
              "surface-container": "#181818",
              "on-tertiary-fixed-variant": "#7c2e00",
              "secondary-container": "#29487f",
              "on-primary-fixed": "#002020",
              "surface-bright": "#393939",
              "secondary-fixed-dim": "#adc7ff",
              "surface-container-highest": "#353534",
              "on-primary": "#003738",
              "primary-fixed": "#5af8fb",
              "tertiary-fixed-dim": "#ffb695",
              "surface-dim": "#131313",
              "on-secondary-fixed-variant": "#26467c",
              "on-primary-fixed-variant": "#004f51",
              "tertiary": "#ffb695",
              "primary-container": "#00a1a3",
              "outline-variant": "#414754",
              "inverse-primary": "#00696b",
              "error": "#ffb4ab",
              "on-surface-variant": "#c1c6d7",
              "surface-container-high": "#2a2a2a",
              "on-secondary-container": "#9bb8f6",
              "secondary": "#adc7ff",
              "on-primary-container": "#002f30",
              "on-tertiary-container": "#4c1a00",
              "error-container": "#93000a",
              "tertiary-container": "#ef6719",
              "primary": "#2ddbde",
              "tertiary-fixed": "#ffdbcc",
              "surface-variant": "#353534",
              "surface-container-lowest": "#0e0e0e",
              "on-tertiary-fixed": "#351000",
              "inverse-surface": "#e5e2e1",
              "inverse-on-surface": "#313030",
              "primary-fixed-dim": "#2ddbde",
              "on-background": "#e5e2e1",
              "surface": "#131313",
              "on-tertiary": "#571e00",
              "on-error-container": "#ffdad6",
              "on-secondary": "#072f64"
            },
            fontFamily : {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
}
export default config;
