
spring.application.name=user-services
server.port=8100
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?currentSchema=user_services&sslmode=require&pgbouncer=true
spring.datasource.username=postgres.bvhsgmqsznayuvlsnior
spring.datasource.password=Karyawanra290705
spring.datasource.hikari.maximum-pool-size=2

spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.default_schema=user_services


jwt.secret.key=ini_adalah_kunci_rahasia_yang_sangat_panjang_dan_aman_123
spring.session.store-type=none
server.servlet.session.persistence=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
