spring.application.name=product-services
server.port=8101
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=appfuxion
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG

jwt.secret.key=ini_adalah_kunci_rahasia_yang_sangat_panjang_dan_aman_123
spring.session.store-type=none
server.servlet.session.persistence=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
