<<<<<<< HEAD
spring.application.name=discovery-server
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
=======
spring.application.name=KaryaWarna
>>>>>>> 50cb809535f81a8daea9cd19c23c1f4634851d49
